name: .NET

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: noeTaskManagerService.Primary

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

  build-and-push-to-render:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore
        working-directory: noeTaskManagerService.Primary

      - name: Build
        run: dotnet build --no-restore -c Release
        working-directory: noeTaskManagerService.Primary

      - name: Test
        run: dotnet test --no-build -c Release
        working-directory: noeTaskManagerService.Primary
        env:
          MongoDB:ConnectionString: ${{secrets.MONGO_DB_CONNECTION_STRING}}
          JWT:Issuer: ${{secrets.JWT_ISSUER}}
          JWT:Audience: ${{secrets.JWT_AUDIENCE}}
          JWT:SecretKey: ${{secrets.JWT_SECRET_KEY}}

      - name: Deploy to Render
        run: curl -X POST -d '{}' YOUR_RENDER_DEPLOY_HOOK_URL
        env:
          YOUR_RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
